Initial Commit
Attempt at create trait based state machine, but it fails with:

 $ cargo run
    Compiling expr-traits-1 v0.1.0 (/home/wink/prgs/rust/myrepos/trait-based-state-machine)
 error[E0503]: cannot use `switch.light_on` because it was mutably borrowed
   --> src/main.rs:36:13
    |
 33 |     switch.current_state.process(&mut switch);
    |                                  ----------- borrow of `switch` occurs here
 ...
 36 |     assert!(switch.light_on == false);
    |             ^^^^^^^^^^^^^^^
    |             |
    |             use of borrowed `switch`
    |             borrow later used here

 For more information about this error, try `rustc --explain E0503`.
 error: could not compile `expr-traits-1` due to previous error